version: '3.9'

services:

  db:
    build: ./db
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${DOCKER_POSTGRES_PORT}"

  backend:
    build: ./backend
    env_file:
      - .env
    container_name: backend
    command: ["/wait.sh", "db", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${DOCKER_POSTGRES_PORT}/${POSTGRES_DATABASE}
    depends_on:
      - db


  frontend:
    build: ./frontend
    container_name: frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "${FRONTEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - backend

volumes:
  dbdata:
